export const menu_items = [
    {
      id: 1,
      name: "Margherita Pizza",
      description: "Fresh tomatoes, mozzarella, and basil",
      price: 15.99,
      category: "Pizza",
    },
    {
      id: 2,
      name: "Spaghetti Bolognese",
      description: "Spaghetti with ground beef and tomato sauce",
      price: 16.99,
      category: "Pasta",
    },
    {
      id: 3,
      name: "Chicken Fajitas",
      description: "Sliced chicken, bell peppers, onions, and tortillas",
      price: 18.99,
      category: "Mexican",
    },
    {
      id: 4,
      name: "Veggie Burger",
      description: "Black bean patty, lettuce, tomato, and avocado",
      price: 14.99,
      category: "Burgers",
    },
    {
      id: 5,
      name: "Grilled Salmon",
      description: "Fresh salmon, lemon, and herbs",
      price: 22.99,
      category: "Seafood",
    },
    {
      id: 6,
      name: "Chicken Caesar Salad",
      description: "Romaine lettuce, grilled chicken, and Caesar dressing",
      price: 13.99,
      category: "Salads",
    },
    {
      id: 7,
      name: "Meatball Sub",
      description: "Meatballs, marinara sauce, and melted mozzarella",
      price: 12.99,
      category: "Sandwiches",
    },
    {
      id: 8,
      name: "Quesadillas",
      description: "Tortillas, cheese, and choice of chicken or steak",
      price: 10.99,
      category: "Mexican",
    },
    {
      id: 9,
      name: "Fried Chicken Tenders",
      description: "Breaded and fried chicken tenders with dipping sauce",
      price: 11.99,
      category: "Appetizers",
    },
    {
      id: 10,
      name: "Greek Salad",
      description: "Tomatoes, cucumbers, feta cheese, and olives",
      price: 12.99,
      category: "Salads",
    },
    {
      id: 11,
      name: "Soft Drinks",
      description: "Coke, Diet Coke, Sprite, Root Beer",
      price: 2.99,
      category: "Drinks",
    },
    {
      id: 12,
      name: "Iced Tea",
      description: "Sweet or Bitter tea",
      price: 2.49,
      category: "Drinks",
    },
    {
      id: 13,
      name: "Lemonade",
      description: "Freshly squeezed lemonade",
      price: 3.49,
      category: "Drinks",
    },
    {
      id: 14,
      name: "Coffee",
      description: "Hot or iced coffee",
      price: 2.49,
      category: "Drinks",
    },
    {
      id: 15,
      name: "Beer",
      description: "Domestic or imported beer",
      price: 5.99,
      category: "Drinks",
    },
    {
      id: 16,
      name: "Wine",
      description: "Red, white, or sparkling wine",
      price: 7.99,
      category: "Drinks",
    },
    {
      id: 17,
      name: "Fresh Juice",
      description: "Orange, apple, or cranberry juice",
      price: 4.99,
      category: "Drinks",
    },
    {
      id: 18,
      name: "Smoothies",
      description: "Blend of yogurt, fruit, and honey",
      price: 5.99,
      category: "Drinks",
    },
    {
      id: 19,
      name: "Milkshakes",
      description: "Thick and creamy milkshake",
      price: 6.99,
      category: "Drinks",
    },
    {
      id: 20,
      name: "Bottled Water",
      description: "Still or sparkling water",
      price: 3.99,
      category: "Drinks",
    },
  ];
  